### ISSUE TITLE
Talk proposal: Web Components

### ISSUE THREAD

**Issue by mafiuss** [wizeline/FE.X#10]

**Comment by mafiuss** [comment]
Great!, thx @josebreijo can you please assign it to me?

**Comment by josebreijo** [comment]
@mafiuss can you give more info, which kind of talk ( lightning / full ) and describe more about the topic. We're still in the process of defining templates for this kind of issues.

**Comment by mafiuss** [comment]
- Mentioning the specifications under the webcomponents umbrella:
Custom Elements
The Custom Elements specification lays the foundation for designing and using new types of DOM elements.
Shadow DOM
The shadow DOM specification defines how to use encapsulated style and markup in web components.
HTML imports
The HTML imports specification defines the inclusion and reuse of HTML documents in other HTML documents.
HTML Template
The HTML template element specification defines how to declare fragments of markup that go unused at page load, but can be instantiated later on at runtime.

- Why I think this is relevant for modern web development
- Probably a demo?

**Comment by josebreijo** [comment]
@mafiuss we have two formats for talks, 5-ish minutes (lightning) or 20-40-ish minutes (full). Which one of this suits best your needs?

**Comment by mafiuss** [comment]
slides: https://docs.google.com/presentation/d/1LKUYCmufQA1Hw3N1-uzQ2p8gVbkPllk57wd0z7XWJ3M/edit?usp=sharing
