### ISSUE TITLE
Talk Proposal - Progressive WebApps

### ISSUE THREAD

**Issue by mafiuss** [wizeline/FE.X#11]
I would like to talk as a follow up of my webcoponents talk, about Progressive Web Applications
- Fast
- Reliable
- Engaging
Discuss service workers, http2, SSL

**Comment by mafiuss** [comment]
https://developers.google.com/web/progressive-web-apps/checklist

**Comment by memorammstein** [comment]
Date TBD but, probably in 4 to 5 weeks from now, does that work for you?

**Comment by mafiuss** [comment]
It works! :)

**Comment by mafiuss** [comment]
[Presentation](https://docs.google.com/presentation/d/19M2z69MUnr6H0eJE_UeZk5gcPaviq3rMqSO6VqLNhu0/edit?usp=sharing)

**Comment by mafiuss** [comment]
[Recording](https://drive.google.com/file/d/1W_xKL8D2IWi0NGEQ8CPC9V8rra-nObH4/view?usp=sharing)

**Comment by ederchrono** [comment]
Awesome session 👏
