### ISSUE TITLE
Talk Proposal - CSS Modules

### ISSUE THREAD

**Issue by TheMightyPenguin** [wizeline/FE.X#13]
# Lightning Talk Proposal

* What are CSS Modules?
* Why bother using them?
* Quick demo with react
* Lessons learned so far with CSS Modules

**Comment by memorammstein** [comment]
@TheMightyPenguin Hi, do you already have this talk prepared or think you can have it ready for this Thursday (Jun 7th)?

**Comment by TheMightyPenguin** [comment]
Don't think I'll have it ready for Jun 7 :(

**Comment by memorammstein** [comment]
Jun 14 is the date 😎
