### ISSUE TITLE
⚡️ On functional programming and recursion ⚡️

### ISSUE THREAD

**Issue by josebreijo** [wizeline/FE.X#14]
A friend needed to turn an excel table data into dependant `<select>` elements for his webpage. The data needed to be grouped on each level, so basically the idea was to convert that table into a tree.

Purpose:

1. Show how using FP and recursion can lead to beautiful and straightforward solutions.
2. Discuss different approaches to this problem.
3. Spread the ❤️ for FP.

Note: this would be a nice follow up for @salvadorbfm ⚡️ talk.

**Comment by memorammstein** [comment]
Jun 14 is the date 😎
