### ISSUE TITLE
Persistent Data Structures

### ISSUE THREAD

**Issue by javierjmx2000** [wizeline/FE.X#16]
Immutable and persistent data structures; why they’re cool and how they work.

Agenda:
1. **Why they're cool**. Discuss the definitions of _pure function_, _functional programming_ and _state_, and how immutability benefits development.
2. **How they work**. Explain the _algorithm_ and the _data structure_ behind persistent data structures and how they achieve _the same performance_ than traditional data structures.
3. **Tools**. Review and _demo_ some of the tools we have at our disposal.

Approximate duration: 45 minutes.

**Comment by memorammstein** [comment]
Sounds 👌, specially "Explain the algorithm and the data structure behind persistent data structures and how they achieve the same performance than traditional data structures."
