### ISSUE TITLE
lighting talks README

### ISSUE THREAD

**Issue by jfer-rubio** [wizeline/FE.X#2]
How to submit a lighting talk
How to suggest a lighting talk
How to give a lighting talk
Timing

**Comment by salvadorbfm** [comment]
I have some points here:

- Lighting Talks must be maximum 10 mins
- Lighting Talks doesn't have a necessary format
- Lighting Talks can be a simple demo of a new feature of "developer tools"

For submissions, I would suggest:

- Describe your topic?
- Time? 
- Needs additional equipment besides de projector?


What do you think?

`xoxo`

**Comment by josejbreijo** [comment]
@salvadorbfm We just defined the docs in [this PR](https://github.com/wizeline/FE.X/pull/7). Feel free to review it. Those are not final, and all the feedback will be added 👍
