### ISSUE TITLE
FE.X web presence

### ISSUE THREAD

**Issue by memorammstein** [wizeline/FE.X#8]
We probably need a page/webapp.This might be as simple as a static page or as fancy as a cutting-edge web application, depending on what we end up wanting to do with it.

Some things that we might want to include into the page are:
- Upcoming and past events
- Resources and tools

**Comment by memorammstein** [comment]
Some considerations:
We should define how all FE.X-related information is going to be flowing between this repo, the slack channel, the proposed website, a possible newsletter, etc. We need to keep things simple and as straightforward as possible.

**Comment by ederchrono** [comment]
I'd recommend a simple github hosted page in this same repo, so if anyone wants to edit something they can do a PR. We might only need a wizeline subdomain `fex.wizeline.com` ? or would you prefer to buy one independently?

**Comment by memorammstein** [comment]
I think this is what @salvadorbfm is going to take care of with the google sites page
